########################
## docker-rusbash-dev ##
########################
## Оглавление
##  
##  1. Базовый образ и разработчики
##  2. Установить локаль ru_RU.UTF-8
##  3. Установить docker и docker-compose
##

# 1. Базовый образ и разработчики
FROM ubuntu:16.04
MAINTAINER German Manvelov <4gekkman@gmail.com>

# 2. Установить локаль ru_RU.UTF-8
ENV LANG C.UTF-8

# 3. Установить docker и docker-compose
RUN apt-get update && apt-get install -y \   
      docker.io \
      curl \
    && \
      curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && \
      chmod +x /usr/local/bin/docker-compose
