########################
## docker-rusbash-dev ##
########################
## Оглавление
##  
##  1. Базовый образ и разработчики
##  2. Установить локаль ru_RU.UTF-8
##  3. Установить docker и docker-compose
##

# 1. Базовый образ и разработчики
FROM ubuntu:16.04
MAINTAINER German Manvelov <4gekkman@gmail.com>

# 2. Установить локаль ru_RU.UTF-8
ENV LANG C.UTF-8

# 3. Установить docker и docker-compose
RUN apt-get update -qq && apt-get install -qqy \
    apt-transport-https \
    ca-certificates \
    curl \
    lxc \
    iptables
RUN curl -sSL https://get.docker.com/ | sh



    
    
