########################
## docker-rusbash-dev ##
########################
## Оглавление
##  
##  1. Базовый образ и разработчики
##

# 1. Базовый образ и разработчики
FROM ubuntu:16.04
MAINTAINER German Manvelov <4gekkman@gmail.com>

# 2. Установить локаль ru_RU.UTF-8
COPY locale /etc/default/locale
RUN locale-gen ru_RU.UTF-8 &&\
  DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales


